import Head from 'next/head'

import ListColumns from '@/components/ListColumns'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tech System Test</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <ListColumns />
    </>
  );
}
